---

- hosts: all
  remote_user: jenkins
  become: yes
  vars_files:
    - /home/jenkins/vault.yml
  ansible_become_password: {{ BECOME_PASS }}

  tasks:
  - name: pull php_app image
    docker_image:
      name: ysherian/repo99:php_app_image
      source: pull
      
  - name: Stop a container
    docker_container:
      name: 
      - php_app
      - mysqli
      state: stopped

  - name: remove container
    docker_container:
      name: 
      - php_app
      - mysqli
      state: absent
      
  - name: start container
    docker_container:
      name: mysqli
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      volumes:
      - ./php/online-shopping-system/database/onlineshop.sql:/docker-entrypoint-initdb.d/onlineshop.sql
      env:
        MYSQL_ROOT_PASSWORD: {{MYSQL_PASS_ROOT}}
            MYSQL_DATABASE: {{MYSQL_NAME}}
            MYSQL_USER: {{MYSQL_USER}}
            MYSQL_PASSWORD: {{MYSQL_PASS}}

  - name: start container
    docker_container:
      name: php_app
      image: php_app_image
      links:
      - "mysqli:db"
      state: started

