---

- hosts: all
  remote_user: jenkins
  become: yes
  vars_files:
    - /home/jenkins/vault.yml
  ansible_become_password: {{ BECOME_PASS }}

  tasks:    
  - name: Stop a container
    docker_container:
      name: 
      - php_app
      - mysqli
      state: stopped

  - name: remove container
    docker_container:
      name: 
      - php_app
      - mysqli
      state: absent
      
  - name: start DB
    docker_container:
      name: mysqli
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      exposed_ports:
      - 6033:3306
      env:
        MYSQL_ROOT_PASSWORD: {{MYSQL_PASS_ROOT}}
            MYSQL_DATABASE: {{MYSQL_NAME}}
            MYSQL_USER: {{MYSQL_USER}}
            MYSQL_PASSWORD: {{MYSQL_PASS}}
      

  - name: start php_app
    docker_container:
      name: php_app
      image: ysherian/repo99:php_app_image
      links:
      - "mysqli:db"
      state: started

